# Generated by Django 2.0.5 on 2018-05-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashier_name', models.CharField(max_length=250)),
                ('cashier_last_name', models.CharField(max_length=250)),
                ('contact_number', models.IntegerField()),
                ('cashier_email', models.EmailField(blank=True, max_length=70)),
                ('status', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
            ],
        ),
    ]
