# Generated by Django 2.0.5 on 2018-05-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='cashier_email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
